name: Deploy Main Branch

permissions:
  contents: write
  pages: write

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to GitHub Pages (root)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          target-folder: .
          clean: false  # Don't delete /dev/ folder
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
